"""Compatibility facade for crawler DB operations.

This package re-exports stable public functions while the implementation
lives in smaller focused modules.
"""

from agents.crawler.db.professors import (
    UpsertEntityResult,
    ensure_professor_affiliation,
    upsert_academician,
    upsert_academician_with_status,
    upsert_professor,
    upsert_professor_with_status,
)
from agents.crawler.db.page_cache import (
    get_cached_fetch_result,
    upsert_page_cache,
)
from agents.crawler.db.graph import (
    get_graph_node_by_key,
    graph_node_key,
    list_ready_graph_nodes,
    mark_graph_node_status,
    record_graph_node_result,
    upsert_graph_edge,
    upsert_graph_node,
)
from agents.crawler.db.schema import (
    ProfessorIdentityRepairCandidate,
    ProfessorIdentityRepairSummary,
    ensure_runtime_schema,
    list_professor_identity_repair_candidates,
    repair_professor_identity_data,
)
from agents.crawler.db.steward import (
    add_data_quality_audit,
    create_steward_run,
    delete_professor_duplicates_for_academician,
    finish_steward_run,
    hard_delete_professor,
    list_professor_academician_duplicates,
    match_academician_for_professor,
    merge_into_academician_from_professor,
)
from agents.crawler.db.tasks import (
    list_recoverable_crawl_tasks,
    log_extraction_failure,
    recover_stale_in_progress_crawl_tasks,
    set_crawl_task_status,
    summarize_crawl_task_status,
    upsert_crawl_task,
)
from agents.crawler.db.university import (
    SubOrgUnitSectionCandidate,
    cleanup_org_unit_scope_pollution,
    cleanup_excluded_org_units,
    count_academicians,
    count_professors,
    count_retryable_fetch_failure_urls,
    ensure_university_meta,
    get_or_create_org_unit,
    get_university_status,
    is_url_crawled,
    list_sub_department_section_candidates,
    list_org_units,
    list_retryable_fetch_failure_urls,
    load_university_targets_from_csv,
    log_crawl,
    merge_sub_department_sections,
    set_org_unit_status,
    set_university_status,
)

__all__ = [
    "cleanup_excluded_org_units",
    "cleanup_org_unit_scope_pollution",
    "count_academicians",
    "count_professors",
    "count_retryable_fetch_failure_urls",
    "create_steward_run",
    "delete_professor_duplicates_for_academician",
    "finish_steward_run",
    "add_data_quality_audit",
    "ensure_professor_affiliation",
    "ensure_runtime_schema",
    "ensure_university_meta",
    "get_or_create_org_unit",
    "get_cached_fetch_result",
    "get_graph_node_by_key",
    "get_university_status",
    "graph_node_key",
    "is_url_crawled",
    "list_ready_graph_nodes",
    "list_sub_department_section_candidates",
    "list_org_units",
    "list_professor_academician_duplicates",
    "list_recoverable_crawl_tasks",
    "list_retryable_fetch_failure_urls",
    "load_university_targets_from_csv",
    "log_crawl",
    "log_extraction_failure",
    "match_academician_for_professor",
    "mark_graph_node_status",
    "merge_into_academician_from_professor",
    "recover_stale_in_progress_crawl_tasks",
    "record_graph_node_result",
    "merge_sub_department_sections",
    "hard_delete_professor",
    "list_professor_identity_repair_candidates",
    "ProfessorIdentityRepairCandidate",
    "ProfessorIdentityRepairSummary",
    "repair_professor_identity_data",
    "UpsertEntityResult",
    "SubOrgUnitSectionCandidate",
    "set_crawl_task_status",
    "set_org_unit_status",
    "set_university_status",
    "summarize_crawl_task_status",
    "upsert_academician",
    "upsert_academician_with_status",
    "upsert_crawl_task",
    "upsert_graph_edge",
    "upsert_graph_node",
    "upsert_page_cache",
    "upsert_professor",
    "upsert_professor_with_status",
]
